### ISSUE TITLE
Filters should not implement `Base.step`

### ISSUE THREAD

**Issue by lassepe** [sisl/GaussianFilters.jl#18]
To add to the wish-list  that @zsunberg  started in #14 here is a small suggestion from my side:

IMHO you should not implement `Base.step` for the filter because the notion of "step" here is different from what `Base` refers to. By importing `Base.step` ...

https://github.com/sisl/GaussianFilters.jl/blob/72fec3caccdf24a0089170c60a189d4c0e10f698/src/GaussianFilters.jl#L8

... you add a method to the `Base.step` function object which has the following [documented behavior](https://docs.julialang.org/en/latest/base/collections/#Base.step).

```
Base.step — Function.

step(r)

Get the step size of an AbstractRange object.
```
.. which is more of a "stepsize" and arguably a horrible name to be occupied by `Base` in the first place.

**Comment by jamgochiana** [comment]
Great point. Updating GMPHD Filter to follow along similar structure as kalman-class filters with separate calls to an predict, measure, and prune function, all wrapped in update. Fixed in https://github.com/sisl/GaussianFilters.jl/commit/ae0699d8a2e0342edd1b73e7e3fefb3e675bc660. Will implement rest of requests and rework docs/examples. Keep 'em comin!
